import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import alice from "../public/alice.jpeg";
import tools from "../public/tools.png";
import recipes from "../public/recipes.jpeg";
import BookNook from "../public/BookNook.jpeg";
import password from "../public/password.jpeg";
import scheduler from "../public/scheduler.jpeg";
import JavaLocator from "../public/JavaLocator.jpeg";
import SQL from "../public/SQL.png";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Alice Silva Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:pd-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">create by alice</h1>
            {/* <a target="_blank" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"><Document file="https://drive.google.com/file/d/15ZNDb-tNN1a94L9YJev1iqKV5gydLDdp/view?usp=sharing"/>Resume</a> */}
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Alice Silva</h2>
            <h3 className="text-2xl py-2 md:text-3xl">Software Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Classical violinist turned software developer. Powered by coffee and curiosity. Based in Charlotte, NC.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/alice-silva-b698791ab/" target="_blank" rel="noreferrer"><AiFillLinkedin /> </a>
            <a href="https://github.com/alicessilva22" target="_blank" rel="noreferrer"><AiFillGithub /></a>
          </div>
          <div className="flex justify-center mt-20">
            <Image className="rounded-full" src={alice} />
          </div>
        </section>

        <section>
          <div className="py-2 text-center shadow-lg p-10 rounded-xl my-10">

            <Image src={tools} width={100} height={100} />


            <h2 className="py-4 text-2xl text-teal-600">Tools I use</h2>

            <p className="text-gray-800 py-1">HTML</p>
            <p className="text-gray-800 py-1">CSS</p>
            <p className="text-gray-800 py-1">JavaScript</p>
            <p className="text-gray-800 py-1">MongoDB</p>
            <p className="text-gray-800 py-1">Express</p>
            <p className="text-gray-800 py-1">React</p>
            <p className="text-gray-800 py-1">Node</p>

          </div>

          <section>
            <div>
              <h3 className="text-3xl py-2">Portfolio</h3>
              <p className="text-md py-2  leading-8 text-gray-800">
                Hello! This is Alice, I am a Software Developer with experience in JavaScript and the MERN stack: MongoDB, Express, React, Node. I work with software development, design, and testing.</p>
                
                <p className="text-md py-2 leading-8 text-gray-800">Fast-learner, hard-worker, and creative problem-solver, I strive to create a more intuitive and user-friendly experience while employing best coding practices and object-oriented programming techniques.</p>
               
                <p className="text-md py-2 leading-8 text-gray-800">I am experienced working with teams and contributing to open source projects using Git version control.</p>
             

            </div>

            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="shadow-xl basis-1/3 flex-1">
              <a href="https://varuntanna.github.io/ProjectOne/index.html" target="_blank" rel="noreferrer">
                <Image src={recipes} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" class="transform transition-all hover:scale-75" />
                </a>
              </div>
              <div className="shadow-xl basis-1/3 flex-1">
                <a href="https://github.com/kleylakb89/book-nook" target="_blank" rel="noreferrer">
                <Image src={BookNook} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" class="transform transition-all hover:scale-75"/>
                </a>
              </div>
              <div className="shadow-xl basis-1/3 flex-1">
                <a href="https://alicessilva22.github.io/Password-Generator/" target="_blank" rel="noreferrer">
                <Image src={password} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" class="transform transition-all hover:scale-75"/>
                </a>
              </div>
              <div className="shadow-xl basis-1/3 flex-1">
                <a href="https://alicessilva22.github.io/Calendar-Module05/" target="_blank" rel="noreferrer">
                <Image src={scheduler} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" class="transform transition-all hover:scale-75"/>
                </a>
              </div>
              <div className="shadow-xl basis-1/3 flex-1">
                <a href="https://github.com/alicessilva22/Java-Locator" target="_blank" rel="noreferrer">
                <Image src={JavaLocator} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" class="transform transition-all hover:scale-75"/>
                </a>
              </div>
              <div className="shadow-xl basis-1/3 flex-1">
                <a href="https://youtu.be/quNzAkuk2MA" target="_blank" rel="noreferrer">
                <Image src={SQL} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" class="transform transition-all hover:scale-75" />
                </a>
              </div>
            </div>


          </section>

        </section>
      </main>
    </div>
  );
}